### ISSUE TITLE
Breakout: Two Bugs

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#25]
https://drive.google.com/file/d/0B-ofvgCKHd68Qmd6VHhvZ28yTnM/view

Ball can get trapped on the edges of the window and from there it can never be rescued.

Paddle can go past the edges of the screen. It shouldn't.

**Comment by ZigaByte** [comment]
Fixed Paddle and Ball

Paddle now had a maximum speed and cannot teleport. It can also not go past the screen.

Ball should now not get trapped due to a countdown timer for bounce implemented.  Ball can only bounce every 10 updates along each axis. (timing can be changed if needed)

**Comment by Jeremy-Barnes** [comment]
Interesting solution for the trapped ball. Having not looked at the code, I dont get how that helps. Could you give me the cliffs notes of why that helps?

One concern about that solution, what happens if it strikes the paddle between those 10 updates? Does it sail through the paddle? Or if its ricocheting off lots of blocks?

**Comment by ZigaByte** [comment]
I am pretty sure the problem was that the ball hit the wall (triggered the collision and its either horizontal or vertical velocity got negated so that the ball bounced on either the x or y axis), then in the next update didn't get far enough for the collision not to trigger again. Meaning the ball's velocity was again pointing into the wall and got stuck in a vicious cycle.

My solution was that after the ball bounces of a wall, it can not bounce again on the same axis for a set amount of ticks. So if it hits the wall, it cannot hit it again for 10 ticks. If it hits the corner for example, that is ok, since the timers are axis based; the ball can bounce twice at a time so long as it is not on the same axis.

10 ticks is really not much and the ball doesn't travel far before it is able to bounce again, but far enough to escape the previous collision box.
